### ISSUE TITLE
add bubble helmet units

### ISSUE THREAD

**Issue by genomejim** [genomejim/fsf#1]
for space and underwater scenes..units will need bubble helmets....example sprite has been generated but needs to be split and prefab with bubble helmet created from "animated player"  
we should do the same for Science and Superstition humanoid units

**Comment by jeldred** [comment]
https://github.com/genomejim/fsf/blob/master/Assets/jim_multiple_split_bubblehelmet.png

**Comment by genomejim** [comment]
added bubble helmet player and crappy underwater skybox to scene1
